# -*- coding: utf-8 -*-
# Generated by Django 1.9a1 on 2016-04-25 03:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
