# -*- coding: utf-8 -*-
# Generated by Django 1.9a1 on 2016-04-25 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spc', '0003_auto_20160425_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performingdetail',
            name='datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='performingtracking',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
