# -*- coding: utf-8 -*-
# Generated by Django 1.9a1 on 2016-04-25 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spc', '0005_auto_20160425_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionbatchmaster',
            name='batchname',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
