# -*- coding: utf-8 -*-
# Generated by Django 1.9a1 on 2016-04-26 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spc', '0007_remove_productionbatchdetails_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionbatchdetails',
            name='sn',
        ),
        migrations.AddField(
            model_name='productionbatchdetails',
            name='sn',
            field=models.ManyToManyField(to='spc.PerformingTracking'),
        ),
    ]
