# -*- coding: utf-8 -*-
# Generated by Django 1.9a1 on 2016-04-26 08:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('spc', '0008_auto_20160426_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionbatchdetails',
            name='sn',
        ),
        migrations.AddField(
            model_name='productionbatchdetails',
            name='sn',
            field=models.CharField(default=datetime.datetime(2016, 4, 26, 8, 32, 16, 137533, tzinfo=utc), max_length=50, verbose_name='DUT serial number'),
            preserve_default=False,
        ),
    ]
